FROM node:21-alpine AS build
WORKDIR /app

COPY ./frontend .
RUN npm install
RUN npm run build
# Serve Application using Nginx Server
FROM nginx:alpine
COPY --from=build /app/dist/frontend/ /usr/share/nginx/html
EXPOSE 80