services:
  memo_db_service:
    image: mysql
    ports:
      - '3307:3307'
    env_file:
      - ./api/.env

  memo_api_service:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    depends_on:
      - memo_db_service
    links:
      - memo_db_service
    volumes:
      - ./api/src:/memo-api/src
      - /memo-api/node_modules
