FROM node:21 as develop

WORKDIR /memo-api

COPY . .

RUN npm install
RUN npm run build
EXPOSE 3000

CMD [ "npm", "run", "start:dev" ]

FROM node:21 as prod

WORKDIR /memo-api

COPY . .

RUN npm install
RUN npm run build
EXPOSE 3000

CMD [ "node", "dist/main" ]